spring:
  application:
    name: feed-send
  data:
    mongodb:
      username: admin
      password: 1234
      database: feed-send
      authentication-database: admin
      uri: mongodb://admin:1234@localhost/feed-send?authSource=admin
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 0