eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    preferIpAddress: true
spring:
  application:
    name: feed-eureka
server:
  port: 8761
